# Generated by Django 5.0.6 on 2024-06-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_type', models.CharField(max_length=100, verbose_name='Тип населенного пункта')),
            ],
            options={
                'verbose_name': 'Тип города',
                'verbose_name_plural': 'Типы городов',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1, verbose_name='пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.AlterModelOptions(
            name='activity_logs',
            options={'verbose_name': 'Логи активности', 'verbose_name_plural': 'Логи активности'},
        ),
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name': 'Перевозчик', 'verbose_name_plural': 'Перевозчики'},
        ),
        migrations.AlterModelOptions(
            name='cruise_type',
            options={'verbose_name': 'Тип рейса', 'verbose_name_plural': 'Тип рейса'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплата'},
        ),
        migrations.AlterModelOptions(
            name='registration_method',
            options={'verbose_name': 'Способ оформления', 'verbose_name_plural': 'Способ оформления'},
        ),
        migrations.RemoveField(
            model_name='activity_logs',
            name='log_id',
        ),
        migrations.RemoveField(
            model_name='buses',
            name='bus_id',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='carrier_id',
        ),
        migrations.RemoveField(
            model_name='carrier_organizations',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='countrys',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='cruise_route',
            name='cruise_route_id',
        ),
        migrations.RemoveField(
            model_name='cruise_type',
            name='cruise_id',
        ),
        migrations.RemoveField(
            model_name='cruises',
            name='cruise_id',
        ),
        migrations.RemoveField(
            model_name='discounts',
            name='discount_id',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='employes',
            name='employe_id',
        ),
        migrations.RemoveField(
            model_name='passengers',
            name='passenger_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='registration_method',
            name='method_id',
        ),
        migrations.RemoveField(
            model_name='stations',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='stations',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='tariffs',
            name='Tariff_id',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_id',
        ),
        migrations.AlterField(
            model_name='cruises',
            name='city_arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_arrival', to='DataBase.cities', verbose_name='город прибытия'),
        ),
        migrations.AlterField(
            model_name='cruises',
            name='destination_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='DataBase.cities', verbose_name='город отправления'),
        ),
        migrations.AlterField(
            model_name='registration_method',
            name='description',
            field=models.CharField(max_length=50, verbose_name='оформление билета'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.districts', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.city_type', verbose_name='тип населенного пункта'),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.gender', verbose_name='пол'),
        ),
    ]
