# Generated by Django 5.0.6 on 2024-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_logs',
            options={'verbose_name': 'Логи активности', 'verbose_name_plural': 'Логи активности'},
        ),
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name': 'Перевозчик', 'verbose_name_plural': 'Перевозчики'},
        ),
        migrations.AlterModelOptions(
            name='cruise_type',
            options={'verbose_name': 'Тип рейса', 'verbose_name_plural': 'Тип рейса'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплата'},
        ),
        migrations.AlterModelOptions(
            name='registration_method',
            options={'verbose_name': 'Способ оформления', 'verbose_name_plural': 'Способ оформления'},
        ),
        migrations.AlterField(
            model_name='regions',
            name='region_id',
            field=models.IntegerField(unique=True, verbose_name='регион id'),
        ),
        migrations.AlterField(
            model_name='registration_method',
            name='description',
            field=models.CharField(max_length=50, verbose_name='оформление билета'),
        ),
    ]
